config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  resources :blogs do
    resources :comments
  end  
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end  
  get "search", to: 'blogs#search'
  post "search", to: 'blogs#search'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, :description, presence: true
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "description", "id", "id_value", "image", "title", "updated_at", "user_id"]
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :blog
    belongs_to :parent, class_name: "Comment", optional: true
    has_many :comments, foreign_key: :parent_id
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :confirmable, :timeoutable
  has_many :blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :update_allowed_parameters, if: :devise_controller?
    before_action :set_query
    protected
    def set_query
        @blog_search = Blog.ransack(params[:q])
    end
    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :mobile, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :mobile, :email, :password, :current_password)}
    end
    def after_sign_in_path_for(resource_or_scope)
        blogs_path    
    end
    def after_sign_out_path_for(resource_or_scope)
        new_user_session_path
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all.paginate(page: params[:page], per_page: 9)
  end
  def search
    @blog_search = Blog.ransack(params[:q])
    @query = @blog_search.result(distinct: true).paginate(page: params[:page], per_page: 9)
  end
  def new
    @blog = Blog.new
  end
  def create
    @user = current_user
    @blog = @user.blogs.new(blog_params)
    if @blog.save
      redirect_to @blog
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @blog = Blog.find(params[:id])
  end
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def show
    @blog = Blog.find(params[:id])
    @comment = @blog.comments.where(parent_id: nil).order(created_at: :desc)
  end
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end
  private
  def blog_params
    params.require(:blog).permit(:title, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.build
    end
    def create
        @user = current_user
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.new(comment_params)
        @comment.user_id = @user.id
        if @comment.save
          BlogsChannel.broadcast_to(@blog, @comment.content)
          redirect_to @blog
        else
          redirect_to @blog
        end
      end
    def destroy
        @blog = Blog.find(params[:blog_id])
        @comment = @blog.comments.find(params[:id])
        @comment.destroy
        BlogsChannel.broadcast_to("blogs_channel", { comment_id: @comment.id, action: 'delete' })
        redirect_to @blog
    end
    private
    def comment_params
        params.require(:comment).permit(:content, :user_id, :blog_id, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/blogs/_search.html.erb
<%= form_for(@blog_search, url: search_path, method: :get) do |blog| %>
  <%= blog.search_field :title_i_cont_any, placeholder: "Search...", class: "search-field" %>
  <%= blog.submit "Search", class: "search-button" %>
<% end %>

app/views/blogs/edit.html.erb
<%= link_to "<- Back", blogs_path, class: "back_button" %>
<center><h1>Edit Blog</h1></center>
<%= form_with model: @blog, html: { class: 'blog-form' } do |form| %>
  <br><br><br>
  <div class="form-group">
    <%= form.label :title, class: "blog_form_label" %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
  </div>
  <br><br>
  <div class="form-group">
    <%= form.label :description, class: "blog_form_label" %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Enter Description' %>
  </div>
  <%= form.submit 'Update', class: 'btn btn-primary' %>
<% end %>

app/views/blogs/index.html.erb
<div class="header">
  <%= button_to "+ New", new_blog_path, method: :get, class: 'new-button' %>
  <%= render 'blogs/search' %>
  <% if user_signed_in? %>
  <% user = current_user %>
  <%= user.name %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'logout-button' %>
  <%end%>
</div>
<center><h1>All blogs</h1></center>
<div class="blogs-container">
  <% @blogs.each do |blog| %>
    <div class="blog-card">
      <div class="blog-card-content">
        <h2 class="blog_title_index_page"><%= link_to blog.title, blog_path(blog) %></h2>
        <% @user = User.find(blog.user_id) %>
        <b>By: <i><%= @user.name %></i></b>
        <p><%= truncate(blog.description, length: 200) %></p>
      </div>
      <div class="blog-card-actions">
        <div class="actions-inner">
          <%= link_to "Edit", edit_blog_path(blog), class: "edit-link" %>
          <%= button_to "Delete", blog_path(blog), method: :delete, data: { confirm: "Are you sure you want to delete this blog?" }, class: "delete-link" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="blogs_pagination">
  <%= will_paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<%= link_to "<- Back", blogs_path, class: "back_button" %>
<center><h1>Create Blog</h1></center>
<%= form_with model: @blog, html: { class: 'blog-form' } do |form| %>
  <br><br><br>
  <div class="form-group">
    <%= form.label :title, class: "blog_form_label" %>
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter Title' %>
  </div>
  <br><br>
  <div class="form-group">
    <%= form.label :description, class: "blog_form_label" %>
    <%= form.text_area :description, class: 'form-control', placeholder: 'Enter Description' %>
  </div>
  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/blogs/search.html.erb
<div class="header">
  <%= button_to "+ New", new_blog_path, method: :get, class: 'new-button' %>
  <%= render 'blogs/search' %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'logout-button' %>
</div>
<% if @query.count == 0 %>
    <h2>No blog with this name</h2>
<%end%>
<% if @query.count() != 0 %>
    <h2><%= @query.count() %> Results</h2>
<% end %>
<div class="blogs-container">
  <% @query.each do |blog| %>
    <div class="blog-card">
      <h2><%= link_to blog.title, blog_path(blog) %></h2>
      <br>
      <p><%= truncate(blog.description, length: 200) %></p>
    </div>
  <% end %>
</div>
<div class="blogs_pagination">
  <%= will_paginate @query %>
</div>

app/views/blogs/show.html.erb
<%= link_to "<- Back", blogs_path, class: "back_button" %>
<div class="blog-content" data-blog-id="<%= @blog.id %>">
<% if @blog.image.present? %>
  <%= image_tag @blog.image.url, alt: @blog.title %>
  </div>
  <div class="blog-text">
  <h1 class = 'blog_title'><%= @blog.title %></h1>
  <p class="blog_description"><%= @blog.description %></p>
  </div>
<% else %>
  <div class="blog-full">
  <h1 class = 'blog_title'><%= @blog.title %></h1>
  <p class = 'blog_description'><%= @blog.description %></p>
  </div>
<% end %>
</div>
<div class = "comment_container">
  <strong class="comment_headline">Comments:</strong><br>
  <% @comment.each do |comment| %>
    <%= render partial: 'comments/comment', locals: { comment: comment } %>
  <% end %>
</div>
<div class="comment_form"><%= render 'comments/form' %></div>
<!-- Include your other HTML content here -->
<script>
  document.addEventListener('DOMContentLoaded', function() {
    App.comment = App.cable.subscriptions.create({ channel: "BlogsChannel", id: <%= @blog.id %> }, {
      connected: function() {
        console.log("Action Cable connected!");
      },
      disconnected: function() {
        console.log("Action Cable disconnected!");
      },
      rejected: function() {
        console.log("Action Cable connection rejected!");
      },
      received: function(data) {
        console.log("Received data from Action Cable:", data);
        // Handle received data
      }
    });
  });
</script>

app/views/comments/_comment.html.erb
<% @user = User.find(comment.user_id) %>
<div class="comment_wrapper">
  <div class="comment_username"><%= @user.name %>:</div>
  <div class="comment_content">
    <%= comment.content %><br>
    <%= button_to "Delete", blog_comment_path(@blog, comment), method: :delete, class: "delete_button" %>
  </div>
  <a href="#" class="reply_form_display" data-comment-id="<%= comment.id %>">reply<br></a>
  <div class="reply_form">
    <%= render partial: 'comments/form', locals: { blog: @blog, comment: comment } %>
  </div>
  <% comment.comments.each do |sub_comment| %>
    <div class="comment_replies">
      <%= render partial: 'comments/comment', locals: { comment: sub_comment } %>
    </div>
  <% end %>
</div>
<script>
document.querySelectorAll('.reply_form_display').forEach((el) =>{
    el.addEventListener('click',(ev) => {
        ev.preventDefault();
        var commentId = el.dataset.commentId;
        var form = el.nextElementSibling.querySelector('form');
        form.querySelector('input[name="comment[parent_id]"]').value = commentId;
        el.nextElementSibling.style = 'display: block;'
    })
})
</script>

app/views/comments/_form.html.erb
<div class="form-wrapper">
  <%= form_with(model: [@blog, @comment], url: blog_comments_path(@blog)) do |f| %>
    <div class="form-field">
      <%= f.hidden_field :parent_id %>
      <%= f.text_field :content, placeholder: "Add a comment" %>
    </div>
    <div class="form-field">
      <%= f.submit "Post" %>
    </div>
  <% end %>
</div>