Rails/Project/shopme/config/routes.rb
Rails.application.routes.draw do
  # get 'search/index'

  devise_for :admins

  # get 'search', to 'searches#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # get 'admins', to: 'devise/registrations#new'

  get "search", to: 'products#search'

  post "search", to: 'products#search'

  root "products#index"

  get "help", to: "help#help"
  
  get "users/sign_up"

  get "sessions/sign_in"

  post "sessions/sign_in", to: "sessions#create"

  delete 'sessions/sign_out', to: "sessions#destroy"
  # delete 'products/delete', to: 'products#destroy'

  resources :users

  # resources :sessions

  resources :products

end

Rails/Project/shopme/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  #  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable, :trackable

  validates_confirmation_of :password
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :mobile

  has_many :products
  
end

Rails/Project/shopme/app/models/concerns/category_data.rb
module Category
    Types = [
        'Beauty',
        'Medicines',
        'Electronic',
        'Sports',
        'Grocery',
        'Fashion'
    ]
end

Rails/Project/shopme/app/models/product.rb
class Product < ApplicationRecord

    validates :name, presence: true, uniqueness: true
    validates :category, inclusion: {in: %w(Beauty Electronic Fashion Grocery Sports Medicines)}
    validates :price, presence: true, numericality: {only_integer: true}
    validates :image, presence: true

    # mount_uploader :image, ProductImageUploader

    has_rich_text :description
    # has_one_attached :description
    
    has_one_attached :image

    belongs_to :admin
    # before_save :store_admin_id_to_product

    # def store_admin_id_to_product
    #     product.admin_id = admin.id
    # end

end

Rails/Project/shopme/app/models/user.rb
class User < ApplicationRecord

    serialize :category, Array

    validates :name, presence: true
    validates :mobile, presence: true, numericality: {only_integer: true}, length: {is: 10}
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, confirmation: true
    validates :password_confirmation, presence: true

    validates_each :email do |record, attr, value|
        record.errors.add(attr, 'Invalid') unless value =~ /[a-z0-9]+@[a-z]+\.[a-z]{2,3}/
    end
    validates_each :mobile do |record, attr, value|
        record.errors.add(attr, 'Invalid') unless value =~ /[7-9]{1}+[0-9]{9}/
    end

end

Rails/Project/shopme/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    add_flash_types :alert, :notice
    
    include Pagy::Backend
    protect_from_forgery with: :exception

    before_action :update_allowed_parameters, if: :devise_controller?

    before_action :set_query

    def set_query
        @products_search = Product.ransack(params[:q])
    end

    protected

    def update_allowed_parameters

        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :mobile, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :mobile, :email, :password, :current_password)}

    end
     
end

Rails/Project/shopme/app/controllers/help_controller.rb
class HelpController < ApplicationController
    def help
    end
end

Rails/Project/shopme/app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index

        if admin_signed_in?


            @admin = current_admin
            @products = @admin.products.all.paginate(page: params[:page], per_page: 3)

        else
            
            @products = Product.all.paginate(page: params[:page], per_page: 3)

        end

    end

    def search

        # @products = Product.where("name LIKE?","%" + params[:q] + "%")
        @products_search = Product.ransack(params[:q])
        @query = @products_search.result(distinct: true)
        # @products = Product.ransack(params[:q])

    end

    def new

        if !(admin_signed_in?)
            redirect_to root_path, notice: "Please sign in admin"
        else
            @product = Product.new
        end

    end

    def create

        if admin_signed_in?

            @admin = current_admin
            @product = @admin.products.new(product_params)

            if @product.save
                redirect_to @product
            else
                render 'new', status: :unprocessable_entity
            end

        end

    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        
        @product = Product.find(params[:id])
        
        if @product.update(product_params)
            redirect_to @product
        else
            render 'edit', status: :unprocessable_entity
        end

    end

    def show

        @product = Product.find(params[:id])
    
    end

    def destroy
        @product = Product.find(params[:id])

        @product.destroy
        redirect_to products_path, status: :see_other
    end

    private

    def product_params
        params.require(:product).permit(:name, :category, :price, :image, :description)
    end

end

Rails/Project/shopme/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def sign_in

        if session[:user_id]
            redirect_to products_path, notice: "User signed in already"
        elsif admin_signed_in?
            redirect_to products_path, notice: "Admin signed in already"
        end

    end

    def new

        # render 'admins/sessions/new'

    end

    def create

        @user = User.find_by_email_and_password(params[:email],params[:password])

        if @user.present? #&& user.authenticate(params[:password])
            session[:user_id]=@user.id
            redirect_to products_path, notice: "User logged in successfuly"
        else
            redirect_to sessions_sign_in_path, notice: "Invalid email or password"
        end
        
    end

    def show
        render 'sign_in'
    end

    def destroy
        session[:user_id] = nil
        redirect_to sessions_sign_in_path, notice: "User signed out successfully"
    end

end

Rails/Project/shopme/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index

    end
    
    def show

    end

    def sign_up

        if session[:user_id]
            redirect_to root_path, notice: "User signed in already"
        elsif admin_signed_in?
            redirect_to root_path, notice: "Admin signed in already"
        else
            @user = User.new
        end

    end
    
    def create

        @user = User.new(user_params)

        if @user.save
            SignUpMailer.with(user: @user).sign_up.deliver_later 
            session[:user_id] = @user.id 
            redirect_to root_path, notice: "Successfully created"
        else
            render 'sign_up', status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :mobile, :email, :password, :password_confirmation, category: :[])
    end

end

Rails/Project/shopme/app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

Rails/Project/shopme/app/helpers/products_helper.rb
module ProductsHelper
end

Rails/Project/shopme/app/helpers/search_helper.rb
module SearchHelper
end

Rails/Project/shopme/app/helpers/searches_helper.rb
module SearchesHelper
end

Rails/Project/shopme/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails/Project/shopme/app/helpers/users_helper.rb
module UsersHelper
end

Rails/Project/shopme/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

Rails/Project/shopme/app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Rails/Project/shopme/app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

Rails/Project/shopme/app/views/help/help.html.erb
<%= button_to "Admin Out", destroy_admin_session_path, method: :delete%>
<%= button_to "User out", sessions_sign_out_path, method: :delete %>

Rails/Project/shopme/app/views/products/edit.html.erb
<p>Edit product details</p>

<%= form_with model: @product do |form| %>
    
    <div class='adding_new_product'>

        <div>
            <%= form.label :name, :class => 'product_form_label' %><br>
            <%= form.text_field :name, :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:name).first %></div>
        </div>

        <div>
            <%= form.label :category, :class => 'product_form_label' %><br>
            <%= form.select :category,['Beauty', 'Electronic', 'Fashion', 'Grocery', 'Sports', 'Medicine'], :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:category).first %></div>
        </div>
            
        <div>    
            <%= form.label :price, :class => 'product_form_label' %><br>
            <%= form.number_field :price, :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:price).first %></div>
        </div>

        <div>
            <%= form.label :image, :class => 'product_form_label' %><br>
            <%= form.file_field :image, :class => 'product_form_file_field', onchange: "imagePreview(event)" %><br>
            <div align='center'><%= image_tag '', id: "preview_product_image" %></div>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:image).first %></div>
        </div>

        <div>    
            <%= form.label :description, :class => 'product_form_label' %><br>
            <%= form.rich_text_area :description, :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:description).first %></div>
        </div>

        <p class='submit_product_details'><%= form.submit %>

    </div>

<%end%>

<script>

    function imagePreview(event) {
        var preview = document.getElementById('preview_product_image');
        preview.src = URL.createObjectURL(event.target.files[0]);
    };

</script>

Rails/Project/shopme/app/views/products/index.html.erb
<div class='products_index_page'>

    <% if @products.count() == 0 %>
        <h2 style='text-align:center'>No product found </h2>
    <% else %>
            
        <p>List of all products</p>
            
            <center>
                
                <table>
                    <tr>
                        <td>Name</td>
                        <td>Action</td>
                    </tr>

                    <% @products.each do |prod| %>
                    <tr>
                            <td><%=image_tag prod.image, class: 'product_index_page_image' %><br><%= prod.name %></td>
                            <td><%= link_to 'Show', product_path(prod) %>
                                <% if admin_signed_in? %>
                                <%= link_to 'Edit', edit_product_path(prod) %>
                                <%= link_to 'Delete', product_path(prod), method: :delete, data: {confirm: "Are you sure?"} %>
                                <% end %>
                            </td>
                    </tr>
                    <% end %>
                </table>

                <%= will_paginate @products %>

            </center>

    <% end %>

</div>

Rails/Project/shopme/app/views/products/new.html.erb
<p>Enter product details</p>

<%= form_with model: @product do |form| %>
    
    <div class='adding_new_product'>

        <div>
            <%= form.label :name, :class => 'product_form_label' %><br>
            <%= form.text_field :name, :class => 'product_form_fields', placeholder: "Name", autofocus: true %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:name).first %></div>
        </div>

        <div>
            <%= form.label :category, :class => 'product_form_label' %><br>
            <%= form.select :category,['Beauty', 'Electronic', 'Fashion', 'Grocery', 'Sports', 'Medicine'], :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:category).first %></div>
        </div>
            
        <div>    
            <%= form.label :price, :class => 'product_form_label' %><br>
            <%= form.number_field :price, :class => 'product_form_fields', placeholder: "Price" %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:price).first %></div>
        </div>

        <div>
            <%= form.label :image, :class => 'product_form_label' %><br>
            <%= form.file_field :image, :class => 'product_form_file_field', onchange: "imagePreview(event)" %><br>
            <div align='center'><%= image_tag '', id: "preview_product_image" %></div>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:image).first %></div>
        </div>

        <div>    
            <%= form.label :description, :class => 'product_form_label' %><br>
            <%= form.rich_text_area :description, :class => 'product_form_fields' %><br>
            <div class = 'sign_up_error' ><%= @product.errors.full_messages_for(:description).first %></div>
        </div>

        <p class='submit_product_details'><%= form.submit %>

    </div>

<%end%>

<script>

    function imagePreview(event) {
        var preview = document.getElementById('preview_product_image');
        preview.src = URL.createObjectURL(event.target.files[0]);
    };

</script>

Rails/Project/shopme/app/views/products/search.html.erb
<div class='searched_product_page'>
<center>

    <% if @query.count == 0 %>
        <h2>No product found</h2>
    <% end %>

        <table>

            <% if @query.count() != 0 %>
            <h2><%= @query.count() %> Results</h2>
            <tr>
                <td>Id</td>
                <td>Name</td>
                <td>Action</td>
            </tr>
            <% end %>

            <% @query.each do |prod| %>
            <tr>
                    <td><%= prod.id %></td>
                    <td><%=image_tag prod.image, class: 'product_index_page_image' %><br><%= prod.name %></td>
                    <td><%= link_to 'Show', product_path(prod) %>
                        <% if admin_signed_in? %>
                        <%= link_to 'Edit', edit_product_path(prod) %>
                        <%= link_to 'Delete', product_path(prod), method: :delete, data: {confirm: "Are you sure?"} %>
                        <% end %>
                    </td>
            </tr>
            <% end %>
        </table>

</center>
</div>

Rails/Project/shopme/app/views/products/show.html.erb
<%= image_tag @product.image, class: "product_image" if @product.image.attached? %>
<div class='product_showing'>

    <h1><%= @product.name %></h1>
    <h3>Category: <%= @product.category %></h3>
    <h3>Rs <%= @product.price %></h3>
    <b>Description:</b><br>
    <%= @product.description %>

</div>

Rails/Project/shopme/app/views/users/index.html.erb
<h1> index page</h1>

Rails/Project/shopme/app/views/users/sign_up.html.erb
<div>

    <p>Sign Up</p>

    <%= form_with model: @user do |form| %>
    
        <div class='user_sign_up_form'>

            <div class='user_sign_up_form_inside_content'>
                <div>
                    <%= form.label :name, :class => 'user_sign_up_label' %>
                    <%= form.text_field :name,placeholder: "Name",autofocus: true, :class => 'user_sign_up_field' %>
                    <b><div class = 'sign_up_error' ><%= @user.errors.full_messages_for(:name).first %></div></b><br>
                </div>

                <div>
                    <%= form.label :mobile, :class => 'user_sign_up_label' %>
                    <%= form.text_field :mobile,placeholder: "Mobile", :class => 'user_sign_up_field' %>
                    <b><div class = 'sign_up_error' > <%= @user.errors.full_messages_for(:mobile).first %> </div></b><br>
                </div>
                    
                <div>
                    <%= form.label :interests, :class => 'user_sign_up_checkbox_label' %>

                        <div class='check_box_sign_up' >
                            <%= check_box_tag 'user[category][]', 'Beauty' %><%= 'Beauty' %>
                            <%= check_box_tag 'user[category][]', 'Medicines' %><%= 'Medicines' %>
                            <%= check_box_tag 'user[category][]', 'Electronic' %><%= 'Electronic' %>
                            <%= check_box_tag 'user[category][]', 'Sports' %><%= 'Sports' %>
                            <%= check_box_tag 'user[category][]', 'Grocery' %><%= 'Grocery' %>
                            <%= check_box_tag 'user[category][]', 'Fashion' %><%= 'Fashion' %>
                        </div>

                    <b><div class = 'sign_up_error' ><%= @user.errors.full_messages_for(:category).first %></div></b><br>
                </div>

                <div>
                    <%= form.label :email, :class => 'user_sign_up_label' %>
                    <%= form.email_field :email,placeholder: "Email", :class => 'user_sign_up_field' %>
                    <b><div class = 'sign_up_error' ><%= @user.errors.full_messages_for(:email).first %></div></b><br>
                </div>

                <div>
                    <%= form.label :password, :class => 'user_sign_up_label' %>
                    <%= form.password_field :password,placeholder: "Password", :class => 'user_sign_up_field' %>
                    <b><div class = 'sign_up_error' ><%= @user.errors.full_messages_for(:password).first %></div></b><br>
                </div>

                <div>
                    <div class='user_sign_up_confirm_password_div'>
                    <%= form.label :confirm_password, :class => 'user_sign_up_label' %>
                    </div>
                    <%= form.password_field :password_confirmation,placeholder: "Confirm password", :class => 'user_sign_up_field' %>
                    <b><div class = 'sign_up_error' ><%= @user.errors.full_messages_for(:password_confirmation).first %></div></b><br>
                </div>

                <p class='user_sign_up_sign_in_link'>Already a member? <%= link_to "Sign in", sessions_sign_in_path %><br></p>

                <p class='user_sign_up_sign_in_link'><%= form.submit %></p>

            </div>

        </div>

    <%end%>

</div>