Rails/Project/hospital_management/config/routes.rb
Rails.application.routes.draw do

  devise_for :patients
  devise_for :doctors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get 'doctors/sign_up', to: 'devise/registrations#new'
  # Defines the root path route ("/")
  root "appointments#main"
  resources :appointments
  get 'appointments/show', to: 'appointments#show'
end

Rails/Project/hospital_management/app/models/appointment.rb
class Appointment < ApplicationRecord

    validates :appointment_date, :appointment_time, :doctor_name, :disease, presence: true

    belongs_to :doctor
    belongs_to :patient

    after_create_commit {broadcast_prepend_to "appointments"}
    after_update_commit {broadcast_replace_to "appointments"}
    after_destroy_commit {broadcast_remove_to "appointments"}

end

Rails/Project/hospital_management/app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable
  
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :specialist
  validates_presence_of :experience
  validates_presence_of :age
  validates_presence_of :location

  validates_confirmation_of :password

  has_many :appointments
  has_many :patients, :through => :appointments

end

Rails/Project/hospital_management/app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :age
  validates_presence_of :gender
  validates_presence_of :mobile

  validates_confirmation_of :password

  has_many :doctors, :through => :appointments
  has_many :appointments, dependent: :delete_all
  
end

Rails/Project/hospital_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    
    before_action :update_allowed_parameters, if: :devise_controller?

    protected

    def update_allowed_parameters

        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :mobile, :age, :gender, :specialist, :experience, :location, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :mobile, :age, :gender, :specialist, :experience, :location, :email, :password, :current_password)}

    end

end

Rails/Project/hospital_management/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
  def main
  end
  
  def show
    @doctor = Doctor.all.load_async
    @patient = Patient.all.load_async
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end
  
  def index
    if patient_signed_in?
      @patient = current_patient 
      @appointments = @patient.appointments 
    end 
    if doctor_signed_in?
      @doctor = current_doctor
      @appointments = @doctor.appointments.includes(:patient)
    end
    respond_to do |format|
      format.html # Render HTML format
    end
  end

  def new
    @appointment = Appointment.new
  end

  def create

    @patient = current_patient
    @appointment = @patient.appointments.new(appointment_params)
    @appointment.doctor_id = Doctor.find_by_name(@appointment.doctor_name)&.id
    
    if @appointment.save
      
      broadcast_to_appointments(@appointment)
      redirect_to appointments_path

    else

      render 'new', status: :unprocessable_entity
      
    end

  end

  def edit

    @appointment = Appointment.find(params[:id])

  end

  def update

    @appointment = Appointment.find(params[:id])
    @appointment.assign_attributes(appointment_params)
    @appointment.doctor_id = Doctor.find_by_name(@appointment.doctor_name)&.id
    if @appointment.update(appointment_params)

      broadcast_to_appointments(@appointment)
      redirect_to appointments_path#(format: :html)
      
    else
      render 'edit' , status: :unprocessable_entity
    end

  end

  def destroy
    @appointment = Appointment.find(params[:id])
    @appointment.destroy
    redirect_to appointments_path,  status: :see_other
  end

  private

  def appointment_params

    params.require(:appointment).permit(:appointment_date, :appointment_time, :disease, :doctor_name)

  end

  def broadcast_to_appointments(appointment)
    turbo_stream.append("appointments",partial: "appointments/appointment",locals: { appointment: appointment })
  end

end

Rails/Project/hospital_management/app/helpers/appointment_helper.rb
module AppointmentHelper
end

Rails/Project/hospital_management/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

Rails/Project/hospital_management/app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_doctor_session_path %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_doctor_registration_path %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_doctor_password_path %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_doctor_confirmation_path %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_doctor_unlock_path %><br />
<% end %>

Rails/Project/hospital_management/app/views/layouts/_header.html.erb
<div class = "header" >
    <ul class = "header_unordered_list" >

        <li><%= link_to "Home", root_path, class: "header_lists" %></li>
        <li><%= link_to "List of Doctors and Patients", appointments_show_path, class: "header_lists" %></li>

        <% if patient_signed_in? || doctor_signed_in? %>
            <li><%= link_to "Appointments", appointments_path, class: "header_lists" %>
        <% end %>

        <% if !(doctor_signed_in?) && !(patient_signed_in?) %>
            <li class = "patient_doctor_login_link"><%= link_to "Patient login", new_patient_session_path, class: "header_lists" %></li>
            <li class = "patient_doctor_login_link"><%= link_to "Doctor login", new_doctor_session_path, class: "header_lists" %></li>
        <% end %>
        
        <% if patient_signed_in? %>
            <li class = "patient_doctor_login_link"><%= link_to "Log out", destroy_patient_session_path, data: {turbo_method: :delete}, class: "header_lists" %></li>
        <% end %>

        <% if doctor_signed_in? %>
        <li class = "patient_doctor_login_link"><%= link_to "Log out", destroy_doctor_session_path, data: {turbo_method: :delete}, class: "header_lists" %></li>
        <% end %>

    </ul>
</div>

Rails/Project/hospital_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HospitalManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>

  </head>

  <body>
  
    <%= render 'layouts/header' %>

    <div class = "flash_notices_and_alerts" >
      <b><%= notice %></b>
      <b><%= alert %></b>
    </div>
    
    <%= yield %>

  </body>
</html>